### PR TITLE
GitHub actions

### PR DESCRIPTION
**Pull request by Darxeal**
This adds a github action that builds python bindings, generates stubs and uploads the output as an artifact. We can discuss what to do with that output, one option is to automatically upload it as a release using [a github action](https://github.com/softprops/action-gh-release). However that could be a separate action, we probably don't want a new release for every new commit to `develop`.

You can see the artifacts and action output [here](https://github.com/Darxeal/RLUtilities/actions/runs/652404459)

TODO: Update python tests and run them in this action

### CODE REVIEW

**Comment by samuelpmish** [comment]
This looks incredible!

A few thoughts:
- I don't mind updating the artifacts every commit, since contributions aren't too frequent. If activity on the repo increases significantly, it might make sense to transition the build/upload artifact actions to being manually trigger.
- I remember seeing something about matrix builds in GitHub actions that might allow us to build against different python versions as well. I'm not sure if RLBot supports multiple versions of python, or if they just pick a specific one and ask users to comply.
- in addition to uploading the artifacts to GitHub, a few additional console commands could update the pip package simultaneously as well (I'm not sure if anyone actually uses it though). GitHub secrets can manage the pypi credentials needed to access the rlutilities pip package. This is probably beyond the scope of this PR though.

Is there anything you wanted to discuss? 

Thank you again, this is a huge quality-of-life improvement, and a useful template for me to use in other personal projects!

**Comment by Darxeal** [comment]
Just to clarify, artifacts aren't the same as releases. Artifact is just the "output" of the action, and it's stored for a limited time. A release is [this for example](https://github.com/samuelpmish/RLUtilities/releases), it has a title and description and its own version tag. I agree that contributions aren't frequent, but it's not worth making a new release when for example someone fixes a typo. I think uploading releases can be done manually, or automatically via a manual trigger like you said.

Supporting multiple python versions and uploading to pip is definitely something to consider for the future. Right now there are already multiple bots in the botpack bundled with their own RLU and I haven't heard of any issues so far. RLBotGUI comes with Python 3.7.

So there are definitely more things to do - release uploading, matrix builds, running tests. I can continue working on this PR or you can merge it, up to you

**Comment by Darxeal** [comment]
- Added the matrix strategy to build for multiple python versions (3.7, 3.8, 3.9). Each job uploads the resulting .pyd as an artifact, and then the `release` job downloads them all, generates stubs and uploads everything as another artifact.
  - See the action here: https://github.com/Darxeal/RLUtilities/actions/runs/661522476
- The `release` job also compresses everything into a .zip and uploads it as an actual release. 
  - See https://github.com/Darxeal/RLUtilities/releases/tag/v1.0.7-matrix-build.0
  - Since a tag is required for each release, there's a step that generates a new tag automatically. The `-matrix-build.0` suffix is there only because my branch is not set as a release branch, only `develop` and `master` is. There the tags should hopefully be simply `v1.0.3`, `v1.0.4`, ...
- Configured CMake to put the .pyd file directly into `python/rlutilities` instead of `python/rlutilities/Release`
- This workflow will now run only on a push to `master` or `develop`. This is because when you are working on a feature on another branch, you don't want to generate a new release every time you push...
- I've decided to not worry about tests for now. Since the stub generator imports the module, the action will fail if the module can't actually be imported from python. So that's already a test on its own.

If you're ok with everything, I think this is ready to be merged

**Comment by samuelpmish** [comment]
Thank you again @Darxeal, this is a really useful contribution.

**Pull request merged**
