### PR TITLE
Update python bindings & more

### PR DESCRIPTION
**Pull request by Darxeal**
See commit messages for full list of changes.
The main change in the python API is that `read_game_information` is now two functions, `read_packet` and `read_field_info`. Field info doesn't change during the match so it only needs to be read once. The most basic bot would now look like this:
```python
class PythonExample(BaseAgent):
    def initialize_agent(self):
        rlutilities.initialize("soccar")
        self.game = Game()
        self.game.read_field_info(self.get_field_info())

    def get_output(self, packet):
        self.game.read_packet(packet)
        ...
```
There are two more things I would like to discuss:
- currently the `Game.cars` vector is empty when `Game` is constructed, so for example you can't do `game.cars[self.index]` before you call `read_packet`. I don't know if it's better to document this so users are aware, or fix this by resizing the vector initially to something like 64.
- the `rlutilities.initialize` API takes a string which represents both the map and gamemode. For the future it would maybe be good to split these into two enums, or possibly make a function to read these automatically from match settings.

When this is completed and merged I would like to create a new official release

### CODE REVIEW

**Comment by samuelpmish** [comment]
These all look like good changes, to me! My only objection is related to duplicating gravity as a member variable on the car, ball, and (statically) on the game objects. To me, it makes the most sense to just have it be basically global, `Game::gravity`. Is there a use-case for introducing it as a member variable for car and ball?

Admittedly, the previously implemented hard-coded gravity wasn't very good.

**Comment by samuelpmish** [comment]
I haven't actually tested the python bindings, but everything seems to build okay for me with MSVC 16.8.2 and clang-cl 10.0.0

**Comment by Darxeal** [comment]
Regarding gravity, yeah you're right it makes more sense to have it global. Theoretically someone could come up with a gamemode where cars and the ball have different gravities but not likely. I was worried about circular imports but I realized that's not an issue here. I'll rewrite it.
Can you also give me an opinion on the two things I pointed out originally?

**Comment by samuelpmish** [comment]
> There are two more things I would like to discuss:
> 
> * currently the `Game.cars` vector is empty when `Game` is constructed, so for example you can't do `game.cars[self.index]` before you call `read_packet`. I don't know if it's better to document this so users are aware, or fix this by resizing the vector initially to something like 64.

We could make the Game object take a number of cars to make it so that it is never in an unknown state. I haven't played with RLBot in a while, but what we really need is the ability to launch a bot with the game parameters, e.g.
```
./botimus.exe -num_players:4 -team:0 -id:1
```
For now I'm tempted to just document that accessing it before reading the first packet is sort of undefined behavior, as resizing doesn't make a lot of sense to me. I'm open to suggestion though!

> * the `rlutilities.initialize` API takes a string which represents both the map and gamemode. For the future it would maybe be good to split these into two enums, or possibly make a function to read these automatically from match settings.

I think this is a good idea, with the caveat that RLU doesn't really have tools to simulate mechanics in dropshot, or the other game modes.

> 
> When this is completed and merged I would like to create a new official release

Sounds like a good idea. I mentioned this briefly in the channel, but I believe we might be able to set up a GitHub action or something to automate the generation of python bindings. Now that `develop` doesn't have any MSVC specific stuff, I think we might be able to use the compilers offered by pypi too.

This is a longshot, but would be a big quality-of-life improvement, if you want to investigate further.

**Comment by Darxeal** [comment]
> We could make the Game object take a number of cars to make it so that it is never in an unknown state. I haven't played with RLBot in a while, but what we really need is the ability to launch a bot with the game parameters, e.g.

the thing is that the number of cars can change during a game (because human players can join and leave). You don't have packet data during initialization, but you can get the number of participants from match settings. By resizing I meant setting the initial size to some number. The maximum amount of bots is 64, that's why I suggested that number. We could make it a parameter in the constructor, but I'm not sure if the one resize on the first `get_output` call is worth complicating the API.

> I think this is a good idea, with the caveat that RLU doesn't really have tools to simulate mechanics in dropshot, or the other game modes.

Dropshot or hoops doesn't have any different mechanics than soccar, only the ball parameters change and RLU does already support it. If we do enums, we simply have values for only those we support. If we do match settings, we'll have to print out a warning when something isn't supported.

> Sounds like a good idea. I mentioned this briefly in the channel, but I believe we might be able to set up a GitHub action or something to automate the generation of python bindings. Now that develop doesn't have any MSVC specific stuff, I think we might be able to use the compilers offered by pypi too.
This is a longshot, but would be a big quality-of-life improvement, if you want to investigate further.

Yeah this would be nice! But we won't be able to make changes in the API without breaking bots, unless someone adds virtual environments with version pinning to RLBot, and I imagine that's not easy

**Review by samuelpmish — APPROVED** [review]
Looks good to me, let me know if there's any other details you want to include or if it's ready to merge now.

**Comment by Darxeal** [comment]
I think it's ready, I can make another PR if I find something that I wanna change later. Thanks for reviewing!

**Pull request merged**
