### PR TITLE
specialized vec<2> and vec<3>

### PR DESCRIPTION
**Pull request by kipje13**

### CODE REVIEW

**Comment by samuelpmish** [comment]
Could you write a little performance benchmark to demonstrate that the change does not appreciably slow down the previous implementation? I'm imagining a little https://github.com/google/benchmark program that does a Reorient simulation or something (quite a bit of vec3 arithmetic in that mechanic) before and after the change.

**Comment by kipje13** [comment]
> Could you write a little performance benchmark to demonstrate that the change does not appreciably slow down the previous implementation?

I have benchmarked `vec<3>` both with the `cross` and `dot` functions.

Before:
```
-----------------------------------------------------
Benchmark           Time             CPU   Iterations
-----------------------------------------------------
BM_cross         1.83 ns         1.84 ns    407272727
BM_dot          0.265 ns        0.266 ns   1000000000
```
After:
```
-----------------------------------------------------
Benchmark           Time             CPU   Iterations
-----------------------------------------------------
BM_cross         1.92 ns         1.90 ns    344615385
BM_dot          0.261 ns        0.266 ns   1000000000
```

**Comment by kipje13** [comment]
These previous benchmarks were not very meaningfull because most stuff got optimized out. These following benchmarks should be more usefull. 

Before:
```
------------------------------------------------------
Benchmark            Time             CPU   Iterations
------------------------------------------------------
BM_cross          12.1 ns         12.3 ns     56000000
BM_dot            3.16 ns         3.21 ns    224000000
BM_reorient        263 ns          261 ns      2635294
```

After:
```
------------------------------------------------------
Benchmark            Time             CPU   Iterations
------------------------------------------------------
BM_cross          1.84 ns         1.84 ns    373333333
BM_dot            2.36 ns         2.35 ns    298666667
BM_reorient        430 ns          433 ns      1659259
```

The reorient simulation mostly uses non-specialized functions, these perform slightly worse when used with specialized vectors. I have found a significant performance boost after creating a specialized functions for `dot(vec<3>, vec<3>)`, from 4.49ns to 2.35ns. I believe that the reorient function could find similar improvements.

**Comment by samuelpmish** [comment]
good find on the initializer_list slowdowns!

**Pull request merged**
